### ISSUE TITLE
req.original.body undefined in Express 4, but new Express body-parser middleware is of no help

### ISSUE THREAD

**Issue by bradisbell** [cmawhorter/hmmac#11]
I see that the plain scheme is using `req.original.body` to try to get the request body data.  In Express 4.x, this doesn't exist.  I added the body-parser middleware (https://github.com/expressjs/body-parser) but this breaks HMMAC:

```
[TypeError: Invalid non-string/buffer chunk]
[Error: Hmmac::_sign: Unable to sign the request]
```

What is the suggested method for dealing with this situation?  Other parts of my application use body-parser, but of course I can alter the order in which I load my middleware.  I would be leery of re-stringifying the JSON within HMMAC in case a JSON formatting difference causes the canonical request to not match what was sent from the client, even if the data within JSON is equivalent.

**Comment by cmawhorter** [comment]
I was looking into this when I realized the problem is likely that you need to include the hmmac middleware prior to body-parser middleware. 

Middleware is executed in order, so body-parser is probably turning req.body into an object before hmmac gets to it.  

If that's not it report back and you can use the untested/suspect workaround below.

I'm going to leave this open to remind me to document this to avoid confusion in the future.

```javascript
// Include/require prior to calling hmmac. 
// it monkey patches crypto to coerce data into a string.  it'd probably be a good idea to 
// make it ignore Buffers
var crypto = require('crypto');
var _Hmac_update = crypto.Hmac.prototype.update;
crypto.Hmac.prototype.update = function(data, encoding) {
  if (typeof data !== 'string') {
    data = String(data);
  }
  return _Hmac_update.call(this, data, encoding);
};
```

And here's a test showing it working:

```javascript
var crypto = require('crypto');

var _Hmac_update = crypto.Hmac.prototype.update;
crypto.Hmac.prototype.update = function(data, encoding) {
  if (typeof data !== 'string') {
    data = String(data);
  }
  return _Hmac_update.call(this, data, encoding);
};

var algo = 'sha1';
var key = 'blah';
var message = 'the message';
var digest = 'hex';
var o = { message: message };

Object.defineProperty(o, 'toString', {
  value: function() {
    return o.message;
  }
});

var shouldBe = crypto.createHmac(algo, key).update(message).digest(digest);
var is = crypto.createHmac(algo, key).update(o).digest(digest);

// REPL breaks if try/catch not on one line
try { crypto.createHmac(algo, key).update({}).digest(digest); } catch (err) { console.log('this is supposed to error', err); }
console.log('this will work', shouldBe);
console.log('this should work', is);
if (shouldBe !== is) {
  throw new Error('Did not match');
}

console.log('Yay.');
process.exit(0);

```

**Comment by bradisbell** [comment]
Thanks for the reply.  I did try swapping the order of body-parser and hmmac (or removing body-parser completely) but this does not solve the problem.  (`req.original.body` is undefined in these cases.)

I'll give your code a try tonight.  Thanks!

**Comment by cmawhorter** [comment]
Weird.  I'll take a closer look tonight too.  I coulda swore that I have
used with express 4 without a problem.

**Comment by cmawhorter** [comment]
Finally had a minute to take a look and it looks like there is no problem here.

I actually read the [express docs on req.body](http://expressjs.com/api.html#req.body) this time and it seems the opposite is true and body-parser prior to including hmmac otherwise req.body will be undefined.  

Curious they didn't just make req.body a readablestream.  I'm also going to update the readme to make this clear.
