### ISSUE TITLE
GET requests error

### ISSUE THREAD

**Issue by alenpesikan** [cmawhorter/hmmac#15]
It doesn't work well for GET requests. Only POST & PUT

**Comment by cmawhorter** [comment]
depending on the server and client, sometimes the request body will be evaluated to `null` or `undefined`.  

likely what's happening is req.body is undefined and being converted to the string "undefined" which is then being used to calculate the compare signature.

i __think__ doing `req.body = req.body || '';` prior to hmmac will resolve the issue, but like i said, it depends on the server/client being used.

i'll leave this open.  this project isn't dead but has been dormant because it Worked for Me and any issue had a decent workaround.  

i'm planning to ship a v1.0 sooner than later
